bbc:
  url: "https://www.bbc.com/news/world/africa"
  selectors:
  - "h2[data-testid='card-headline']"

aljazeera:
  url: "https://www.aljazeera.com/where/africa/"
  selectors:
    article_link: "a.u-clickable-card__link"


guardian:
  url: "https://www.theguardian.com/global-development"
  selectors:
    article_link: "a[data-link-name='article']"


reuters:
  url: "https://www.reuters.com/world/africa/"
  selectors:
    article_link: "a[data-testid='Heading']"
    publication_time: "time[data-testid='Label']"